name: brf_dnn_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py311h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - asttokens==3.0.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - executing==2.2.0
      - fonttools==4.57.0
      - igraph==0.11.8
      - ipykernel==6.29.5
      - ipython==9.1.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - leidenalg==0.10.2
      - louvain==0.8.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - numba==0.61.2
      - numpy==1.26.4
      - packaging==24.2
      - pandas==1.5.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - prompt-toolkit==3.0.50
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.1
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-louvain==0.16
      - pytz==2025.2
      - pyzmq==26.4.0
      - scikit-learn==1.5.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wcwidth==0.2.13
prefix: /home/hice1/imusayeva3/.conda/envs/brf_dnn_env
