name: ml_project
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - ipywidgets
  - jupyterlab
  - flake8
  - ruff
  - mypy
  - black
  - pytorch
  - tensorflow
  - keras
  - xgboost
  - statsmodels
  - scipy
  - umap-learn
  - fastparquet
  - pyarrow
  - plotly
  - pydantic
  - pip
  - pip:
      - kaleido
      - statsmodels
      - playwright